### ISSUE TITLE
Model cannot be saved

### ISSUE THREAD

**Issue by tnybny** [Visual-Behavior/detr-tensorflow#15]
Trying to save the model using `tf.keras.model.save_model` leads to a TypeError:
```
File "detr_tf/networks/transformer.py", line 211, in call
key_mem = memory + pos_encoding
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```

**Comment by PhanTask** [comment]
You may use model.save_weights('params.h5') and model.load_weights('params.h5') to save and load your model.
