### ISSUE TITLE
    AttributeError: 'Tensor' object has no attribute 'to_tensor'

### ISSUE THREAD

**Issue by Sequential-circuits** [Visual-Behavior/detr-tensorflow#2]
python train_coco.py --datadir /root/detr-tensorflow/coco --batch_size 8  --target_batch 32 --log

I get the error:
_**AttributeError: in user code:

    /root/detr-tensorflow/training.py:31 run_val_step  *
        total_loss, log = get_losses(m_outputs, t_bbox, t_class, config)
    /root/detr-tensorflow/loss/loss.py:30 get_losses  *
        losses = get_detr_losses(m_outputs, t_bbox, t_class, config)
    /root/detr-tensorflow/loss/loss.py:129 get_detr_losses  *
        t_bbox = t_bbox.to_tensor()

    AttributeError: 'Tensor' object has no attribute 'to_tensor'**_

My setup:
GeForce GTX 1050  
Driver Version: 460.27.04    
CUDA Version: 11.2
Tensorflow 2.4.0
CUDNN 8_8.0.5.39-1 for cuda11.1
Python 3.8.5

**Comment by thibo73800** [comment]
Hello,

The code din't get fully tested under Tf 2.4 yet. But I solved your issue in this commit: https://github.com/Visual-Behavior/detr-tensorflow/commit/81b2e072170aa1fbdd35e8877c8fe3b4668c0336

Have a nice week end,
Thibault

**Comment by Sequential-circuits** [comment]
Great, this did solve the issue, thanks

However, now I get:
/root/detr-tensorflow/loss/compute_map.py:101: RuntimeWarning: invalid value encountered in true_divide
  overlaps = intersections / union
compute_map error. e= unhashable type: 'numpy.ndarray'
Validation step: [0],    ce: [4.64]      giou : [1.09]   l1 : [0.66]     time : [0.00]

And it keeps repeasting the 2 last lines apparently forever. The dataset is just one single picture for just testing this system, so I understand it shouldn't repeat that text so many times

Look forward and thanks again

Al
