### ISSUE TITLE
compute_map error. e= unhashable type: 'numpy.ndarray'

### ISSUE THREAD

**Issue by Sequential-circuits** [Visual-Behavior/detr-tensorflow#3]
I keep getting compute_map error. e= unhashable type: 'numpy.ndarray' when training

**Comment by thibo73800** [comment]
Sounds weird since the map is not supposed to be computed during training. 

Next week we'll release a step by step tutorial on how to use the repository to finetune on a custom dataset.
In the meanwhile can you please provide me with enough code for me to reproduce your issue?

Thanks

**Comment by Sequential-circuits** [comment]
The code is the one from train_coco.py 

The command given was python train_coco.py --datadir /root/detr-tensorflow/coco --batch_size 1  --target_batch 1 --log

**Comment by Sequential-circuits** [comment]
Never mind, that error seems to be gone. I was actually able to train a simple model on a V100 with 32 Gb, but if I try to do the same with a GTX1050 with 2 Gb I get:
Traceback (most recent call last):
  File "train_coco.py", line 74, in <module>
    run_finetuning(config)
  File "train_coco.py", line 58, in run_finetuning
    training.fit(detr, train_dt, optimzers, config, epoch_nb, CLASS_NAME)
  File "/root/detr-tensorflow/training.py", line 46, in fit
    m_outputs, total_loss, log, gradient_steps = run_train_step(model, images, t_bbox, t_class, optimizers, config)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 862, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[252,256,2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node gradient_tape/detr_finetuning/detr/transformer/encoder/layer_5/linear2/MatMul/MatMul_1 (defined at /root/detr-tensorflow/optimizers.py:115) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_run_train_step_69433]

Errors may have originated from an input operation.
Input Source operations connected to node gradient_tape/detr_finetuning/detr/transformer/encoder/layer_5/linear2/MatMul/MatMul_1:
 detr_finetuning/detr/transformer/encoder/layer_5/dropout_11/dropout_1/Mul_1 (defined at /root/detr-tensorflow/networks/transformer.py:174)

Function call stack:
run_train_step

Obviously, it is running out of memory: not much that can be done there. Hope this is useful information

**Comment by Sequential-circuits** [comment]
Thanks, but that hasn't shown again. Probably just needed a reboot. :)

**Comment by joseribeiro99** [comment]
I am having that issue too! It happens with finetune_hardhat.py
