### ISSUE TITLE
imgaug File Not Found

### ISSUE THREAD

**Issue by gautamHCSCV** [Visual-Behavior/detr-tensorflow#36]
Dear authors,
You have imported 'imgaug' file in many places but it is missing from the required location. The code gives error on running. Please let me know how to resolve the issue.

@thibo73800 @PhanTask @andife

**Comment by joseribeiro99** [comment]
You have an older version, try this:
`pip uninstall imgaug`
`pip install git+https://github.com/aleju/imgaug.git`
