### ISSUE TITLE
Empty Predictions after finetuning

### ISSUE THREAD

**Issue by Yusepp** [Visual-Behavior/detr-tensorflow#42]
I managed to adapt my dataset in a tf csv object format and perform the finetuning. Now I wanted to see some qualitative results running inference and plotting bboxes. I'm using the same code as the webcam inference example but im getting:
```
tf.Tensor([], shape=(0, 4), dtype=float32)
tf.Tensor([], shape=(0,), dtype=int64)
tf.Tensor([], shape=(0,), dtype=float32)
```

as output of the get_model_inference function. Any idea ?

**Comment by ni3s** [comment]
have not worked on webcam but for images below code is working 

from detr_tf.inference import get_model_inference, numpy_bbox_to_image
import matplotlib.pyplot as plt
import numpy as np

for valid_images, target_bbox, target_class in dataset:
    
    m_outputs = detr(valid_images, training=False)
    predicted_bbox, predicted_labels, predicted_scores = get_model_inference(m_outputs, config.background_class, bbox_format="xy_center")

    result = numpy_bbox_to_image(
        np.array(valid_images[0]),
        np.array(predicted_bbox),
        np.array(predicted_labels),
        scores=np.array(predicted_scores),
        class_name=CLASS_NAMES, 
        config=config
    )
    plt.imshow(result)
    plt.show()
    break
