### ISSUE TITLE
Training with a VOC dataset?

### ISSUE THREAD

**Issue by Sequential-circuits** [Visual-Behavior/detr-tensorflow#5]
It is great that this repository works with both VOC and COCO datasets

However, the instructions only say "python eval.py --datadir **/path/to/coco**". 

What about VOC?

**Comment by thibo73800** [comment]
The eval script is just here as an example, but you can can evaluate on VOC by loiding the VOC dataset instead of the COCO dataset. Checkout this tutorial for more info:  https://github.com/Visual-Behavior/detr-tensorflow/blob/main/notebooks/How%20to%20load%20a%20dataset.ipynb
