### ISSUE TITLE
Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10 

### ISSUE THREAD

**Issue by stipra** [Visual-Behavior/detr-tensorflow#8]
Getting this error although the file is there and LD_LIBRARY_PATH is correctly set

**Comment by stipra** [comment]
This is a bug with CUDA 11.2 and tensorflow

I installed CUDA 11.0 and problem fixed

**Comment by thibo73800** [comment]
Great ! Let me know if you need any helps to get started with the repository.
